import Head from "next/head";
import BestAudio from "@/components/BestAudio";
import ProductStack from "@/components/home/ProductStack";
import { createClient } from "contentful";

export async function getStaticProps() {
    console.log("Executing getStaticProps");
    const client = createClient({
        space: process.env.SPACE_ID,
        accessToken: process.env.CONTENT_DELIVERY_TOKEN,
    });

    let assets = {};

    try {
        const [desktop, tablet, mobile] = await Promise.all([
            client.getAsset("3uIGgrCDgySKW5tljIfncv"),
            client.getAsset("1nkmfthd1HXMIFxqpxrbya"),
            client.getAsset("2DTUz7xbHLnQqDxbygtRWA"),
        ]);
        assets = { desktop, tablet, mobile };
        console.log("BestAudio assets loaded successfully");
        // console.log("Assets loaded successfully:", assets);
    } catch (error) {
        console.log("Error loading BestAudio assets");

        // console.log("Error loading assets:", error);
    }

    return { props: { assets } };
}

export default function Home({ assets }) {
    return (
        <>
            <Head>
                <title>Audiophile</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>home</div>
            <ProductStack></ProductStack>
            <BestAudio src={assets} />
        </>
    );
}
