import { createClient } from "contentful";
import Head from "next/head";
import Hero from "@/components/index/Hero";
import Gallery from "@/components/Gallery";
import ProductStack from "@/components/index/ProductStack";
import BestAudio from "@/components/layout/BestAudio";
import Navbar from "@/components/navigation/Navbar";
import logo from "/public/shared-desktop-logo.svg";


export async function getStaticProps() {
  const client = createClient({
    space: process.env.SPACE_ID,
    accessToken: process.env.CONTENT_DELIVERY_TOKEN,
  });

  let assets = {};

  await client
    .getAssets({ limit: 1000 })
    .then((response) => {
      assets = response.items;
    })
    .catch(console.error);

  return { props: { assets } };
}

export default function Home({ assets }) {
  // console.log(assets);
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar logo={logo} assets={assets}></Navbar>
      <Hero assets={assets} />
      <Gallery assets={assets} />
      <ProductStack assets={assets} />
      <BestAudio assets={assets} />
    </>
  );
}
